FROM node:20-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

# Dự án không có login/redux phức tạp, build trực tiếp ra môi trường production để tối ưu tốc độ
RUN npm run build

# Sử dụng một server web siêu nhẹ là 'serve' để chạy production build
RUN npm install -g serve

EXPOSE 3000

CMD ["serve", "-s", "dist", "-l", "3000"]